# Generated by Django 4.2.1 on 2023-05-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_receivable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receivable',
            new_name='ReceivableModel',
        ),
    ]
