# Generated by Django 4.2.1 on 2023-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_receivable_receivablemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersmodel',
            name='uuid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
