# Generated by Django 4.2.1 on 2023-05-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_partnersmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersmodel',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='partnersmodel',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='partnersmodel',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='partnersmodel',
            name='rg_ie',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='partnersmodel',
            name='uuid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
