# Generated by Django 4.2.1 on 2023-05-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_partnersmodel_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartnersModel',
            new_name='Partners',
        ),
        migrations.RenameModel(
            old_name='ReceivableModel',
            new_name='Receivable',
        ),
    ]
