# Generated by Django 4.2.1 on 2023-05-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_partnersmodel_partners_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
