# Generated by Django 4.2.1 on 2023-05-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('app', '0011_alter_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(to='company.company'),
        ),
    ]
