# Generated by Django 4.2.1 on 2023-05-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_user_company_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
